CREATE ROLE videoproc WITH LOGIN PASSWORD 'videoprocSecret';
ALTER ROLE videoproc CREATEDB;
CREATE DATABASE videoproc OWNER videoproc;

GRANT ALL PRIVILEGES ON DATABASE simple_bank_py TO videoproc;

\c videoproc;

GRANT USAGE ON SCHEMA public TO videoproc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO videoproc;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO videoproc;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO videoproc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO videoproc;
