# Generated by Django 4.2 on 2025-04-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("done", "Done"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
